sudo: false
git:
  depth: 1
addons:
  apt:
    packages:
    - bsdtar
    - curl
    - nodejs
    - rsync
script:
  - sh -x ./build.sh
env:
  - THEME_VERSION="0.1.3"
deploy:
  api_key:
    secure: "$DEPLOY_OAUTH_TOKEN"
  file: "target/CLARIN_Horizon-${THEME_VERSION}.tgz"
  on:
    tags: true
  overwrite: true
  provider: releases
  skip_cleanup: true
notifications:
  email:
    on_success: change
    on_failure: always
